### DISCUSSION TITLE
Recommended way to deal with overwriting

### DISCUSSION THREAD

**Discussion by matthiasschaub** [picocss/pico#241] [Help]
I love using pico.css. Using LeafletJS or OpenLayers I embed a map on my website. Since pico.css styles HTML elemtents the elements such as buttons of the embedded map are also styled, but do not look great. See this image.

![image](https://user-images.githubusercontent.com/83658582/191477576-85dffe47-3e1c-437c-aa96-d0deeb5ff9fb.png)

A minimal example can be found here https://github.com/matthiasschaub/pico-map-playground

Relevant code snippets are:

HTML:
```html
        <link rel="stylesheet" href="styles.css" />
        <link rel="stylesheet" href="css/custom.css"/>
        <link rel="stylesheet" href="css/leaflet.css" />
        <script src="js/leaflet.js"></script>
        ...
        <section id="map" aria-label="Map">
            <div class="container" align="center">
                <div class="leaflet-container" id="leafletmap"></div>
            </div>
        </section>
```

custom.css
```css
.leaflet-container {
    height: 600px;
    /* width: 960px; */
    max-width: 100%;
    max-height: 100%;
}
```

Using following css:
```css
.leaflet-container {
  height: 600px;
  /* width: 960px; */
  max-width: 100%;
  max-height: 100%;
}

.leaflet-container [role="button"] {
    all : revert;
}
```
The map will look like this (notice the +/- zoom buttons in the upper left corner and the missing layer buttons)
![image](https://user-images.githubusercontent.com/83658582/191477912-d291a67b-1bc2-47a7-81c1-347f06e52f17.png)

Is there a recommended way in the spirit of pico.css to deal with such cases. E.g. disable styling for the map but keep default style of buttons.

**Comment by wdporter** [comment]
.leaflet-container button {
        * : revert /* or maybe unset */
    }

Not necessarily the "recommended way", just my way.

**Reply by matthiasschaub** [reply]
Thanks for your quick answer!
I changed your suggestion to work in the following way:

```css
.leaflet-container {
  height: 600px;
  /* width: 960px; */
  max-width: 100%;
  max-height: 100%;
}

.leaflet-container [role="button"] {
    all : revert;
}
```
This does remove the style. It removes all styling which I would like to avoid.
![image](https://user-images.githubusercontent.com/83658582/191459758-c87c2f89-fecb-48b0-aa25-43ef0b0edf33.png)
Take note of the +/- zoom buttons in the upper left corner.
