### DISCUSSION TITLE
Unable to click on certain elements after v1.4.2

### DISCUSSION THREAD

**Discussion by ronaldgrn** [picocss/pico#305] [Help] [answered]
I came across an issue where picocss doesn't allow you to click on the crisp.chat bot after version 1.4.2

see https://jsfiddle.net/gy3L0qm4/1/

Does anyone know how to get around this?

**Comment by lucaslarroche** [comment, marked as answer]
Hi @ronaldgrn, 

It's because Crips Chat creates a link (`a`) without an `href`, and Pico considers it disabled.

You can override this behavior with:
```CSS
a[role=button]:not([href]) {
  opacity: .5;
  pointer-events: auto;
}
```

This (wrong) behavior will be removed in version 2.
