### DISCUSSION TITLE
Table row hover

### DISCUSSION THREAD

**Discussion by 8ctopus** [picocss/pico#375] [Ideas]
Thank you for creating `pico`, it's awesome.

I would like to suggest to add a hover effect in tables. I'm no css expert or designer but here's what I did:

```css
table[role=grid] tbody tr:hover {
  filter: brightness(1.5);
}

table[role=grid] tbody tr:hover:nth-child(odd) {
  filter: brightness(1.5);
}
```
