### DISCUSSION TITLE
Contrast Colors Utility Class (Pico v2)

### DISCUSSION THREAD

**Discussion by leoherzog** [picocss/pico#380] [Ideas]
Loving the direction of Pico v2 so far!

My project that uses v2 has a bunch of the following utility classes:

```css
.pico-color-red-contrast {
  color: var(--pico-color-red-600);
}
[data-theme="dark"] .pico-color-red-contrast {
  color: var(--pico-color-red-200);
}

.pico-color-orange-contrast {
  color: var(--pico-color-orange-600);
}
[data-theme="dark"] .pico-color-orange-contrast {
  color: var(--pico-color-orange-200);
}

.pico-color-pumpkin-contrast {
  color: var(--pico-color-pumpkin-600);
}
[data-theme="dark"] .pico-color-pumpkin-contrast {
  color: var(--pico-color-pumpkin-200);
}
/* ... */
```

so that I can apply color to text that is still readable when the theme switches. Should this be included out of the box? I could see this being useful for buttons and such as well.
