### DISCUSSION TITLE
Why does a, [role=link] reassign --pico-primary?

### DISCUSSION THREAD

**Discussion by crumple-zone** [picocss/pico#395] [Help]
A colleague of mine was trying to style a headline, which is also a link, to use the regular text color. He did something like the following but with no effect:

```css
h3 a { color: var(--pico-color}; }
```

After some digging we realized that Pico (v2) is reassigning the Pico color custom property for links:

```css
a, [role=link] {
  --pico-color: var(--pico-primary);
   color: var(--pico-color);
}
```
We couldn't think of why this wouldn't have simply been:

```css
a, [role=link] {
  color: var(--pico-primary);
}
```
It seems like this would have achieved the same visual default without preventing customization. So before we go off overriding it, I thought I'd ask and get a better understanding of the strategy. So why would `--pico-color` get reassigned?

**Note:** I attempted to simplify above code samples to focus on the issue at hand. And also, this question _isn't_ about the wisdom of using the regular text color for a link. 😄 

Thanks!
