### DISCUSSION TITLE
Make Dropdown align on the right side

### DISCUSSION THREAD

**Discussion by MrAmericanMike** [picocss/pico#407] [Help]
I was wondering if it's possible to make a dropdown open aligned to the right side of the trigger and not the left side.

![image](https://github.com/picocss/pico/assets/8037559/666795ff-c98d-45e9-b8bc-901f93e87e54)

I achieved this with a global rule. 

```css
details[role="list"] summary+ul {
	left: unset !important;
}
```

![image](https://github.com/picocss/pico/assets/8037559/9e0c8199-5bb8-4d5f-9756-96f98ef49624)

Is there a built in way to get the same result?
