### DISCUSSION TITLE
Grid Span Utility Class

### DISCUSSION THREAD

**Discussion by pietz** [picocss/pico#508] [Ideas]
I understand that PicoCSS takes a very minimal approach, which is why the grid system is also similarly simple. I still want to suggest utility classes for the span of a grid column because with this the grid becomes a lot more powerful and useful.

I'm making the numbers up as I type but I want to imagine that 50% of people that want to use a grid are too limited with Pico's current offering. The one feature that people will miss the most is defining a column to be wider than one element. Having this option would allow so much more flexibility and yet the implementation is straight forward. I think this easily covers the need of 90% of people without needing custom CSS or the Bootstrap grid on top.

I think the final solution would be something like this:

```css
@media (min-width: 768px) {
    .grid>.span-2 {grid-column: span 2;}
    .grid>.span-3 {grid-column: span 3;}
    .grid>.span-4 {grid-column: span 4;}
}
```

So this...

```html
<div class="grid">
    <div class="span-2">I'm twice as wide...</div>
    <div>...as me</div>
</div>
```

...would work. In my mind `span-2`, `span-3` and `span-4` is more than enough.

What do you think?
