### DISCUSSION TITLE
Dark mode tooltips

### DISCUSSION THREAD

**Discussion by Matojeje** [picocss/pico#542] [Ideas]
I'd say the tooltips are too bright in dark mode, making them hard to read. It would be nice to see responsive tooltips in the future.

I used this to give them secondary colors for now:

```css
@media (prefers-color-scheme: dark) {
  [data-tooltip] {
    --pico-tooltip-background-color: var(--pico-secondary-background);
    --pico-tooltip-color: var(--pico-secondary-inverse);
  }
}
```
