### DISCUSSION TITLE
touch friendly radio button group

### DISCUSSION THREAD

**Discussion by alphatownsman** [picocss/pico#567] [Ideas]
sth like
<img width="389" alt="Screenshot 2024-06-23 at 15 39 58" src="https://github.com/picocss/pico/assets/90480431/c3dec24d-16bd-4c50-b77f-13099f773c4f">

**Comment by dev-willis** [comment]
I do that like this:

Markup:
```html
<div class="radio_group">
	<input type="radio" id="rg-one" name="radio_name">
	<label for="rg-one">One</label>
	<input type="radio" id="rg-two" name="radio_name">
	<label for="rg-two">Two</label>
	<input type="radio" id="rg-three" name="radio_name">
	<label for="rg-three">Three</label>
	<input type="radio" id="rg-four" name="radio_name">
	<label for="rg-four">Four</label>
</div>
```

CSS:
```css
.radio_group{display:flex; justify-content:center;
	input{display:none;}
	label{border:var(--pico-primary) solid var(--pico-border-width); margin:0; padding:1em; display:grid; place-content:center;
		&:first-of-type{border-radius:var(--pico-border-radius) 0 0 var(--pico-border-radius);}
		&:last-of-type{border-radius:0 var(--pico-border-radius) var(--pico-border-radius) 0;}
		&:not(:last-of-type){border-right:0; margin:0;}
		&:hover{background-color:var(--pico-primary); color:#fff;}
	}
	input:checked + label{background-color:var(--pico-primary); color:#fff;}
}
```
