### DISCUSSION TITLE
tooltip line break?

### DISCUSSION THREAD

**Discussion by 8ctopus** [picocss/pico#590] [Help]
How does one add a line break inside a tooltip? I've tried both `\n` and `<br>` without success.
Here's my code sample:

```html
<a href="#" data-tooltip="By default, search will look for an exact match. If you want to search with an open end, use the asterisk: Joh* Doe which will match both John Doe and Johnny Doe" data-placement="left">?</a>
```

**Comment by 8ctopus** [comment]
I didn't find how to do it so I decided to switch to an article instead that I display/hide on hover. Here's the code if someone's interested.

```js

document.addEventListener('DOMContentLoaded', function () {
  const hint = document.querySelector('a#tooltip-hint');
  hint.addEventListener('mouseenter', toggleTooltip);
  hint.addEventListener('mouseleave', toggleTooltip);
});

function toggleTooltip(event) {
  const tooltip = document.querySelector('article#tooltip');

  tooltip.style.display = (tooltip.style.display === 'block') ? 'none' : 'block';
}

```
```css
article#tooltip {
  display: none;
  font-size: 0.875em;
}
```
```html
<a id="tooltip-hint" href="#">?</a>
<article id="tooltip">
  Lorem ipsum sin amet
</article>
```

**Comment by JonSpeare** [comment]
I was thinking the same. Tried \<br> and \n but no dice. Would be a good addition.

**Comment by matt-the-midnight-hacker** [comment]
Not directly a solution but for me using data-placement="left" / data-placement="right" helped to keep the tooltip visible.

**Comment by tommy4st** [comment]
I'm using this to at least allow line breaks if the text is too long:
```css
[data-tooltip]::before {
    max-width: max(100%, 15rem);
    width: max-content;
    white-space: initial;
    text-indent: 0;
}
```
