### DISCUSSION TITLE
Fluid Container Size...

### DISCUSSION THREAD

**Discussion by Deufel** [picocss/pico#633] [Ideas]
This seams like a good idea, But maybe I am missing something; 

```css

/* REPLACE  */
@media (min-width: 576px) {
    .container {
        max-width: 510px;
        padding-right: 0;
        padding-left: 0;
    }
}
@media (min-width: 768px) {
    .container {
        max-width: 700px;
    }
}
@media (min-width: 1024px) {
    .container {
        max-width: 950px;
    }
}
@media (min-width: 1280px) {
    .container {
        max-width: 1200px;
    }
}
@media (min-width: 1536px) {
    .container {
        max-width: 1450px;
    }
} 
```

```css

/* WITH  */
.container {
  width: min(100%, clamp(320px, 90vw, 1450px));
}
```
