### DISCUSSION TITLE
feature request: aside as sidebar

### DISCUSSION THREAD

**Discussion by tacman** [picocss/pico#682] [Ideas]
Kudos for such a great library.

I'd love to have a sidebar.  My primitive implementation is an aside after making everything flex:

```css
body {
    display: flex;
    min-height: 100vh;
    margin: 0;
}
aside {
    width: 220px;
    padding: 1rem;
    border-right: 1px solid var(--pico-muted-border-color);
    background-color: var(--pico-background-color);
}
main {
    flex: 1;
    padding: 2rem;
}
```

And tweaking the base html accordingly.

I don't know how you'd do it to stay consistent with your philosophy, but I figured I'd ask -- I'd love to have a sidebar without having to add my own css.  Thanks!
