### DISCUSSION TITLE
Add col-span helper classes for grid

### DISCUSSION THREAD

**Discussion by harrison314** [picocss/pico#683] [Ideas]
I've been playing around with PicoCSS for a while and I like its use of semantic HTML. But one thing I really miss when using a grid is that I need to split the main area in different ratios, like 2:1.

Eight came up with this solution:
```html
<div class="grid">
  <div class="col-2">
    main content
  </div>
  <div>
   side content or nav
  </div>
</div>
```

```css
.col-1 {
    grid-column: span 1;
}

.col-2 {
    grid-column: span 2;
}

.col-3 {
    grid-column: span 3;
}

.col-4 {
    grid-column: span 4;
}
.col-5 {
    grid-column: span 5;
}
```

Wouldn't it be possible to add something like this directly to the framework?
