### ISSUE TITLE
[Feature Request] Admonitions

### ISSUE THREAD

**Issue by RoyiAvital** [picocss/pico#12]
This is a great and clean `CSS`.

Any chance of having Admonitions.  
Something like in Jupyter will be great: https://jupyterbook.org/content/content-blocks.html.

**Comment by lucaslarroche** [comment]
Thank you.

What would be the HTML code for an admonition?
It is same as an [alert](https://getbootstrap.com/docs/5.0/components/alerts/)?

I try to stick to [official HTML Elements](https://developer.mozilla.org/en-US/docs/Web/HTML/Element) and [ARIA Roles](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles) as much as I can.

[`role="alert"`](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/Alert_Role) looks good at first, but _"Screen readers will instantly start reading out the updated content"_ so it seems irrelevant to me.

But on the other hand, Bootsrap uses `role="alert"` in its [examples](https://getbootstrap.com/docs/5.0/components/alerts/#examples).

**Comment by RoyiAvital** [comment]
I think they use alerts with some customization for other kind of "alerts" such as: Tip, Info, Warning, etc...

**Comment by RoyiAvital** [comment]
@lucaslarroche , Any update on this?

**Comment by lucaslarroche** [comment]
@RoyiAvital, 

I'm open to a pull request in [dev/](https://github.com/picocss/pico/tree/dev) for a [`role="alert"`](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Techniques/Using_the_alert_role) component.
```HTML
<div role="alert"></div>
```
For colors customization, I am thinking about integrating some SCSS mixins.
It would be best to wait until the color variation system is complete before creating new components.

**Comment by mjau-mjau** [comment]
If anyone interested, simple Pico.css alerts, which inherit properties from Pico:
https://codepen.io/mjau-mjau/full/xxjZRGg

**Comment by a-chris** [comment]
@mjau-mjau thank you, that's a great starting point

**Comment by jpshackelford** [comment]
+1 for this to be a standard feature of Picocss. I ❤️ Picocss and an alert system is a very common component.

**Comment by yozachar** [comment]
Could this be re-opened?

**Comment by mediaformat** [comment]
@lucaslarroche is this still relevant? Would you accept a PR?

> [`role="alert"`](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/Alert_Role) looks good at first, but _"Screen readers will instantly start reading out the updated content"_ so it seems irrelevant to me.

I think that for some classes of errors, perhaps even some warnings, `role=alert` is the right choice, while for others such as status updates "post saved",  using [`role="status"`](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Reference/Roles/status_role), would be more appropriate.

**Comment by Slluxx** [comment]
Might not be perfect but works for me.

<img width="578" height="219" alt="Image" src="https://github.com/user-attachments/assets/b5874b88-5e4a-4dcd-bbdb-9da43cb8dbc6" />

```html
<aside data-type="note">
    <header>Note</header>
    <p>This is a note admonition, styled like mkdocs-material.</p>
</aside>
```

```css
aside {
    --admonition-color: var(--pico-primary);
    --admonition-bg: var(--pico-card-sectioning-background-color);

    padding: var(--pico-spacing) var(--pico-spacing) 0;
    margin-bottom: var(--pico-spacing);
    border: 1px solid var(--admonition-color);
    border-radius: var(--pico-border-radius);
    box-shadow: var(--pico-card-box-shadow);
    color: var(--pico-color);
    background: var(--pico-background-color);
}

aside>header {
    display: flex;
    align-items: center;
    gap: 0.6rem;
    font-weight: var(--pico-font-weight);
    padding: 0.6rem 1.25rem;
    margin: calc(var(--pico-spacing) * -1) calc(var(--pico-spacing) * -1) 0;
    border-radius: var(--pico-border-radius) var(--pico-border-radius) 0 0;
    background: var(--admonition-bg);
    color: var(--admonition-color);
}

aside>header::before {
    font-size: 1.1em;
    line-height: 1;
}

aside>header+* {
    margin-top: var(--pico-spacing);
}

aside>header a {
    color: inherit;
    text-decoration: underline;
}

/* Danger / warning */
aside[data-type="danger"],
aside[data-type="warning"] {
    --admonition-color: var(--pico-del-color);
}

aside[data-type="danger"]>header::before,
aside[data-type="warning"]>header::before {
    content: "⚠️";
}

/* Important */
aside[data-type="important"] {
    --admonition-color: var(--pico-ins-color);
}

aside[data-type="important"]>header::before {
    content: "❗";
}

/* Note */
aside[data-type="note"] {
    --admonition-color: var(--pico-primary);
}

aside[data-type="note"]>header::before {
    content: "✏️";
}

/* Tip */
aside[data-type="tip"] {
    --admonition-color: #b8860b;
}

aside[data-type="tip"]>header::before {
    content: "💡";
}
```
