### ISSUE TITLE
Built in padding doesn't apply in React (or Next.js).

### ISSUE THREAD

**Issue by ja1den** [picocss/pico#13]
I want to begin by saying that I love this project. It looks great, and it's really easy to use.

Unfortunately, I've found a bug.

In both [React](https://reactjs.org/) and [Next.js](https://nextjs.org/), all content is placed inside a wrapper `<div>` inside `<body>`.

For example:

```html

<!-- React -->

<body>
  <div id="root">
    <!-- all content goes here -->
  </div>
</body>

<!-- Next.js -->

<body>
  <div id="__next">
    <!-- all content goes here -->
  </div>
</body>

```

This breaks the responsive vertical padding on `<header>`, `<main>`, and `<footer>`, as defined [here](https://picocss.com/docs/#containers) in the documentation, and [here](../blob/master/scss/layout/_sectioning.scss#L21) in the source code.

The fix for this is pretty simple, but it involves putting edge cases for React and Next.js into the framework, which might be something you don't want to do.

I'm proposing changing this part of `layout/_sectioning.scss` (line 21):

```scss
body {
  // ...
}
```

to this:

```scss
body, #__next, #root {
  // ...
}
```

Of course, the CSS version of the framework would also need to be updated.

I'm currently using [patch-package](https://www.npmjs.com/package/patch-package) to make these patches in my own project.

I'm ready to make a pull request if you'd be happy with it, but if not, that's fine too.

**Comment by lucaslarroche** [comment]
Hi @ja1den, 

Thank you.

I will not create a special case for React and Next.js.
I try to keep Pico as neutral as possible, focused on natives HTML elements.

The only thing I could consider is a variable to enable (disabled by default) a container for React and Next.js

```SCSS
// Enable React semantic container
$enable-class-container: false !default;
```

The clean way to override the default semantic container is to disable all the containers in Pico :

`pico-react.scss`
```SCSS
// Enable <header>, <main>, <footer> inside <body> as a container
$enable-semantic-container: false;

// Enable .container and .container-fluid
$enable-class-container: false;

@import "pico";
```
And then import your own container layout :

`pico-react.scss`
```SCSS
@import "layout/react-container";
```

`layout/_react-container.scss`
```SCSS
#root {
  > header,
  > main,
  > footer {
    ...
  }
}
```

But the default Pico style does not have a semantic container.
You don't have to edit the styles to have a container. Just use `.container` or `.container-fluid`.

```HTML
<body>
  <div id="root">
    <header class="container"> ... </header>
    <main class="container"> ... </main>
    <footer class="container"> ... </footer>
  </div>
</body>
```

**Comment by djmtype** [comment]
The `div` between `body` and `main` applies to React, Next and Nuxt, too. I agree Pico should be as neutral as possible. 

Why not this? Example: 

```css
@media (min-width: 768px) {
body > header, body > div[id] header,
body > main, body > div[id] main,
body > footer, body > div[id] footer {
    max-width: 700px;
  }
}
```

**Comment by BK-Modding** [comment]
For anyone still looking for a pure CSS-based solution to this problem, paste the following into one of your app's stylesheets.

```css
@media (min-width: 576px) {
  body > div#root > header,
  body > div#root > main,
  body > div#root > footer,
  section {
    --block-spacing-vertical: calc(var(--spacing) * 2.5);
  }
}
@media (min-width: 768px) {
  body > div#root > header,
  body > div#root > main,
  body > div#root > footer,
  section {
    --block-spacing-vertical: calc(var(--spacing) * 3);
  }
}
@media (min-width: 992px) {
  body > div#root > header,
  body > div#root > main,
  body > div#root > footer,
  section {
    --block-spacing-vertical: calc(var(--spacing) * 3.5);
  }
}
@media (min-width: 1200px) {
  body > div#root > header,
  body > div#root > main,
  body > div#root > footer,
  section {
    --block-spacing-vertical: calc(var(--spacing) * 4);
  }
}

body > div#root > header,
body > div#root > main,
body > div#root > footer {
  width: 100%;
  margin-right: auto;
  margin-left: auto;
  padding: var(--block-spacing-vertical) 0;
}
```

I pulled the relevant declarations out of `css/pico.css` and modified the selector definitions to include `div#root`.

**Comment by bkataru** [comment]
For anyone still looking for a pure CSS-based solution to this problem, paste the following into one of your app's stylesheets.

```css
@media (min-width: 576px) {
  body > div#root > header,
  body > div#root > main,
  body > div#root > footer,
  section {
    --block-spacing-vertical: calc(var(--spacing) * 2.5);
  }
}
@media (min-width: 768px) {
  body > div#root > header,
  body > div#root > main,
  body > div#root > footer,
  section {
    --block-spacing-vertical: calc(var(--spacing) * 3);
  }
}
@media (min-width: 992px) {
  body > div#root > header,
  body > div#root > main,
  body > div#root > footer,
  section {
    --block-spacing-vertical: calc(var(--spacing) * 3.5);
  }
}
@media (min-width: 1200px) {
  body > div#root > header,
  body > div#root > main,
  body > div#root > footer,
  section {
    --block-spacing-vertical: calc(var(--spacing) * 4);
  }
}

body > div#root > header,
body > div#root > main,
body > div#root > footer {
  width: 100%;
  margin-right: auto;
  margin-left: auto;
  padding: var(--block-spacing-vertical) 0;
}
```

I pulled the relevant declarations out of `css/pico.css` and modified the selector definitions to include `div#root`.
