### ISSUE TITLE
Grid idea using grid-template-areas

### ISSUE THREAD

**Issue by PMunch** [picocss/pico#148]
I'm creating a website with Pico, and I'm loving the semantic spirit of the project. But as soon as I wanted to create something slightly different than the single document page the layouting options really fell short. My particular issue came from trying to create a small "code documentation" page with navigation on top, a menu on the left, and content on the right (ref. [Python documentation](https://docs.python.org/3.11/library/stdtypes.html), [C# documentation](https://docs.microsoft.com/en-us/dotnet/api/system.collections.concurrent.concurrentdictionary-2?view=net-6.0)). Turning to the Pico documentation and the "Company" example I could see that the way my gripes where solved there was with custom CSS that defined various sizes of the sidebars. I went digging for something a bit tidier with CSS grid, and stumbled upon `grid-template-areas`. What I ended up with is essentially defining `grid-area` names for the various semantic elements that Pico uses (note I also defined these for `body` as I was just going to use them for layouting the entire page):

```css
body > nav, .grid > nav {
  grid-area: nav;
}
body > main, .grid > main {
  grid-area: main;
}
body > header, .grid > header {
  grid-area: header;
}
body > footer, .grid > footer {
  grid-area: footer;
}
body > aside, .grid > aside {
  grid-area: aside;
}
body > div, .grid > div {
  grid-area: div;
}
```

Then I could simply add my `nav`, `aside`, and `main` to the `body` tag and the only custom CSS I needed was:
```css
body {
  grid-template-areas:
    'nav nav'
    'aside main';
  grid-template-columns: 1fr 4fr;
}
```
Of course that layout isn't responsive, but adding a media query or two wouldn't be too problematic. The thing I really liked about this system was the semantic nature of it, just add your tags, and define where they go and how big everything should be in a simple rule. Given how common certain types of layouts are a lot more prevalent than others it would also be possible to create a few default responsive ones and give them simple names. These could then be selected by just attaching a class to the `body` tag (or to any `.grid` element) and voila your layout has changed.

What I'm proposing is adding this as a very simple yet surprisingly flexible, semantic way of doing layouting in Pico. If you don't like the idea I might just create my own tiny grid extension for Pico with this system should others find it useful.
