### ISSUE TITLE
Tooltip does not close on mobile

### ISSUE THREAD

**Issue by kvetoslavnovak** [picocss/pico#184]
## Describe the issue
  Tooltips do not close on mobile. 
  I believe this may be quite easy to achieve only with css. E.g. see this classic example https://www.w3schools.com/css/css_tooltip.asp using 
```css
.tooltip .tooltiptext {
  visibility: hidden;
}
  
.tooltip:hover .tooltiptext {
  visibility: visible;
}
```

### Current Behavior
The tooltip doesn’t close on mobile. 

### Expected Behavior
The tooltips should close/disappear on mobile if user touch/click elsewhere. 

### Reproduction URL
https://picocss.com/docs/tooltips.html

### Environment
Mobile devices (iOS).
