### ISSUE TITLE
[Feature Request] Html hr line

### ISSUE THREAD

**Issue by janstieler** [picocss/pico#213]
Hi,
I would love to have a simple HTML Line `<hr>` in the standard elements.
Ist a classic Element and the standard looks so ugly.
I would suggest it should looks like the fine line between the modal header and body.

Cheers

**Comment by abernh** [comment]
One [should not use `hr` as a styling-only horizontal line](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/hr)

> While it may still be displayed as a horizontal rule in visual browsers, this element is now defined in semantic terms, rather than presentational terms, so if you wish to draw a horizontal line, you should do so using appropriate CSS.

**Comment by janstieler** [comment]
Your right. But it change not that the `<hr>` looks ugly.
I have not write that I use it not in the semantic way which have changed.

**Comment by abernh** [comment]
That's true. I only assumed :) 
But not having a pre-styled `hr` makes people think why that may be. 

Maybe a good solution could be a prestyled `hr` that does not resemble a full line but rather, like one might have notices sometimes in books, a line with a padding to both sides. Something like

```css
hr{
 border: 0px;
 border-top: 1px;
 border-color: var(--border-color); /* is that the right var? */
 margin: 20% 1em;
 height: 0;
 overflow: hidden;
}
```

This would make for a nice default and prevent people from using it as a layout element.

**Comment by janstieler** [comment]
Yes, a hr ist not so hard to style.
But we talk here about a framework which is orientated on standard elements looks nice.
And it's a little bit agnoying to style the hr new every time. And this is why I use pico.
I have no so overdose style like Bootstrap but I don't have to borne the standard style :) .

And please don't forget that it was published as a feature request from me.
But thank for pointing that is not used like in HTML 4. But a semantic element can also used as a layout element.
I use it often in blogarticles.

**Comment by abernh** [comment]
>  I use it often in blogarticles.
Perfect usage. And I'd say a padded line looks much nicer in the general flow of a text than a hard-full-width line.

**Comment by lucaslarroche** [comment]
It's not documented, but there is a basic style for `<hr />`:
https://github.com/picocss/pico/blob/master/css/pico.css#L1777

```CSS
hr {
  height: 0;
  border: 0;
  border-top: 1px solid var(--muted-border-color);
  color: inherit;
}
```
