### ISSUE TITLE
Customization Doc

### ISSUE THREAD

**Issue by dyaliCode** [picocss/pico#214]
in doc to said if need to change default color we need to put code bellow but not working.

```scss
:root {
  --primary: #e53935;
}
```
