### ISSUE TITLE
Add additional css rules to address Nuxt and similar frameworks

### ISSUE THREAD

**Issue by djmtype** [picocss/pico#222]
Nuxt v3 injects and requires a `div#__nuxt` added to the DOM directly following the `body`. The way Pico's `max-width` rules target `head`, `main` and `footer` is by using direct descenders. For example ,`body > main`. 

Original:  
```css
@media (min-width: 768px) {
body > header,
body > main,
body > footer {
    max-width: 700px;
  }
}
```
While Nuxt contains this one descending `div`, Next contains two descending `div`s. To accommodate both frameworks, maybe: 
```css
@media (min-width: 768px) {
body > header, body > div[id] header,
body > main, body > div[id] main,
body > footer, body > div[id] footer {
    max-width: 700px;
  }
}
```
