### ISSUE TITLE
input type="search" no clear button

### ISSUE THREAD

**Issue by dylanvdmerwe** [picocss/pico#227]
## Describe the issue
When you have an input type of "search", although it looks great and styled, pico has removed (or hidden) the built in close button that is part of the html:

![image](https://user-images.githubusercontent.com/2852839/188017482-c59ac2a6-1b6a-4eb8-adeb-87cc9bc498f5.png)

### Current Behavior
There is no clear button:
![image](https://user-images.githubusercontent.com/2852839/188017594-6d272fc9-6e26-4c29-bd47-4bff296ea125.png)

### Environment
Example: Windows, Chrome/Edge/Firefox

**Comment by jasaldivara** [comment]
I'm having the same issue. Is there a workaround to reenable the clear button?

I'm looking at the browser developer tools, but I cannot find anything that reenables it.

I have this problem either on Google Chrome and Firefox.

**Comment by gigamaster** [comment]
Try this :

```css 
input[type="search"]::-webkit-search-cancel-button {

    -webkit-appearance: initial;
    background-image: url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAB4AAAAeCAYAAAA7MK6iAAAAn0lEQVR42u3UMQrDMBBEUZ9WfQqDmm22EaTyjRMHAlM5K+Y7lb0wnUZPIKHlnutOa+25Z4D++MRBX98MD1V/trSppLKHqj9TTBWKcoUqffbUcbBBEhTjBOV4ja4l4OIAZThEOV6jHO8ARXD+gPPvKMABinGOrnu6gTNUawrcQKNCAQ7QeTxORzle3+sDfjJpPCqhJh7GixZq4rHcc9l5A9qZ+WeBhgEuAAAAAElFTkSuQmCC);
    background-size: 1rem auto;
    background-repeat: no-repeat;
    cursor: pointer;
    display: block;
    height: 16px;
    width: 16px;
    /* px here but you can use rem */
    margin-right: 8px;
}
```
