### ISSUE TITLE
Bug: dotted border-bottom on dropdowns with tooltip

### ISSUE THREAD

**Issue by telamon** [picocss/pico#230]
### Description
A button with a tooltip does not receive an dotted underline but a drop-down does.
Maybe add `:not([role=button])` to filter list?
```css
[data-tooltip]:not(a):not(button):not([role=button]):not(input) {
  border-bottom: 1px dotted;
  text-decoration: none;
  cursor: help;
}
```

### Current Behavior
```html
<details role="list">
  <summary aria-haspopup="listbox" role="button" data-tooltip="Dropdown with Tooltip">🎨</summary>
   <ul role="listbox">...</ul>
</details>
```
![image](https://user-images.githubusercontent.com/148454/188446080-a6f2b5ab-d04f-42a0-b14b-f4248f064b57.png)

### Expected Behavior
No border-bottom.
