### ISSUE TITLE
Styling not working, css variable override

### ISSUE THREAD

**Issue by SlavenGrowy** [picocss/pico#303]
### Current Behavior
1. Copy and paste ["Starter HTML template"](https://picocss.com/docs/)
2. Add a button
3. Add the following `<style>` tag in the `<head>` of the document
``` 	
<style>
      :root {
          --primary: #d81b60;
      }
</style>
```
4. The coloring of the `button` does not change according to the `--primary` css variable.

 
### Expected Behavior
The styling for the button and input should change, according to the `--primary` color
### Reproduction URL
https://codepen.io/slaven-ivanov/pen/GRBdJaK?editors=1000

**Comment by lucaslarroche** [comment]
This "simplified" example in the [documentation](https://picocss.com/docs/customization.html) is confusing. You need to override the CSS variables for the color schemes.
This confusion will be fixed in v2.

Here is the full working example:

```CSS
/* Pink Light scheme (Default) */
/* Can be forced with data-theme="light" */
[data-theme="light"],
:root:not([data-theme="dark"]) {
  --primary: #d81b60;
  --primary-hover: #c2185b;
  --primary-focus: rgba(216, 27, 96, 0.125);
  --primary-inverse: #FFF;
}

/* Pink Dark scheme (Auto) */
/* Automatically enabled if user has Dark mode enabled */
@media only screen and (prefers-color-scheme: dark) {
  :root:not([data-theme="light"]) {
    --primary: #d81b60;
    --primary-hover: #e91e63;
    --primary-focus: rgba(216, 27, 96, 0.25);
    --primary-inverse: #FFF;
  }
}

/* Pink Dark scheme (Forced) */
/* Enabled if forced with data-theme="dark" */
[data-theme="dark"] {
  --primary: #d81b60;
  --primary-hover: #e91e63;
  --primary-focus: rgba(216, 27, 96, 0.25);
  --primary-inverse: #FFF;
}

/* Pink (Common styles) */
:root {
  --form-element-active-border-color: var(--primary);
  --form-element-focus-color: var(--primary-focus);
  --switch-color: var(--primary-inverse);
  --switch-checked-background-color: var(--primary);
}
```
