### ISSUE TITLE
Empty mark tag

### ISSUE THREAD

**Issue by asaf** [picocss/pico#335]
## Describe the issue

Empty `<mark>` tag shows a small empty yellowed string
  
### Expected Behavior

Should show nothing if tag is empty

### Suggested solution

```css
mark:empty {
  padding: 0px;
}
```
