### ISSUE TITLE
Wildcard issue with variable

### ISSUE THREAD

**Issue by Baswazz** [picocss/pico#387]
I want to apply the `--spacer` variable to a child element within a nav but the variable is set to 0 using the wildcard `*`;

```css
nav li>* {
    --spacing: 0;
}
```

For example te space out the icon and label text:

```html
<nav>
  <ul>
    <li>
      <icon> Label
    </li>
  </ul>
</nav>
```

```css
a > :not(:only-child):is(svg) {
	margin-inline-end: var(--spacing);
}
```
  
### Current Behavior
A concise description of the bug.

### Expected Behavior
A concise description of what you expected.

### Reproduction URL
https://jsfiddle.net/k5yd1a3r/

### Environment
Chrome 114.0.5735.198
