### ISSUE TITLE
Better grouping of details content and summary dropdown

### ISSUE THREAD

**Issue by davidbgk** [picocss/pico#409]
* [x] Please search for duplicate or closed issues first.
  
### Current Behavior

For now (v1 and v2) I find the details/summary elements to be a bit disconnected from the actual unfolded content, especially when using the `role="button"`.

<img width="813" alt="Capture d’écran, le 2023-09-27 à 19 00 13" src="https://github.com/picocss/pico/assets/3556/7c4a3706-3af0-421c-a0bf-53508654ff20">

### Expected Behavior

That's the third time I add this to my custom CSS, it's just a suggestion of course:

```css
details {
  border: 1px solid var(--secondary);
  border-radius: var(--border-radius);
  padding: var(--border-radius);
}
```

<img width="809" alt="Capture d’écran, le 2023-09-27 à 19 01 26" src="https://github.com/picocss/pico/assets/3556/7194e305-240b-4de5-b009-aa196e1e56f2">

Maybe it'll help somebody else, I can make a PR for that.

### Reproduction URL

The documentation provides good examples:

* https://picocss.com/docs/accordions.html
* https://v2.picocss.com/docs/accordion
