### ISSUE TITLE
v2: role "group" on buttons

### ISSUE THREAD

**Issue by gp-slick-coder** [picocss/pico#417]
![image](https://github.com/picocss/pico/assets/1906169/6719d6d0-6a13-41e5-a153-16d6b50dbfbd)

I'm not so sure if this is useful. This is totally against good UX.

**Comment by lucaslarroche** [comment]
@gp-slick-coder, do you recommend updating the docs? Or removing the feature (not possible now to avoid a breaking change).

I guess it could be useful for a group of related actions, like:
![image](https://github.com/picocss/pico/assets/23470684/49e399a9-b8a3-4270-b871-664214d7c2da)

**Comment by lucaslarroche** [comment]
Ah, yes, I get it.

I think this style looks broken/buggy:
<img width="300" alt="Screenshot 2024-02-13 at 23 17 21" src="https://github.com/picocss/pico/assets/23470684/b555f53c-7be6-4db2-bee5-a90c1dfe475f">
<img width="223" alt="Screenshot 2024-02-13 at 23 18 09" src="https://github.com/picocss/pico/assets/23470684/3fe6d717-cf13-476d-8f1f-20843f4933f3">
<img width="683" alt="Screenshot 2024-02-13 at 23 24 46" src="https://github.com/picocss/pico/assets/23470684/37680a88-fee8-4dbd-916e-69c619a1603d">

I still prefer this style:

https://github.com/picocss/pico/assets/23470684/22d4f091-ae76-4ffb-b09f-308fa256126d



But I'm open to a better solution.

**Comment by Brian-Pob** [comment]
What about something like this where the whole border of the button in the group is shown instead of a broken border?

https://github.com/picocss/pico/assets/29676413/89a7a896-9dbb-45a0-8043-77d330ec6343

Example from:
https://stackoverflow.com/a/67756667

**Comment by fadrian06** [comment]
### I am having overflow problems on mobile

![Screenshot_20240217-132912.png](https://github.com/picocss/pico/assets/109766973/cb479e09-20f6-4b55-ab31-de9a0ef44cfe)

The third button of the group leaves the container

**Comment by Brian-Pob** [comment]
The issue with the button group overflowing seems to be due to this style rule setting a new horizontal padding of 2rem, which overrides the original horizontal padding of 1rem.

```CSS
[role=group] [role=button], [role=group] [type=button], [role=group] [type=submit], [role=group] button, [role=search] [role=button], [role=search] [type=button], [role=search] [type=submit], [role=search] button {
    --pico-form-element-spacing-horizontal: 2rem;
}
```

![image](https://github.com/picocss/pico/assets/29676413/b21b2baf-f141-4efc-8bb4-cac6c4722a08)

It seems that keeping the padding at 1rem still looks decent while allowing the display to get as small as 306px (smaller than an iPhone SE at 375px) without any overflow issues. See attached screen recording

https://github.com/picocss/pico/assets/29676413/b890334b-ee98-4a64-a8a6-733d735b8bc4
