### ISSUE TITLE
invalid state slider for checkbox switches

### ISSUE THREAD

**Issue by basaran** [picocss/pico#46]
Hello,

While I was testing the pico, I noticed the default error state for the switches seem a little off.

![switch](https://user-images.githubusercontent.com/30809170/138664560-8559a939-b424-40fc-9dec-a3a254afd9b1.gif)

Perhaps something like this would be more appropriate?

```css
[type="checkbox"][role="switch"][aria-invalid] {
    --background-color: var(--switch-color);
    --border-color: var(--switch-background-color);
    --color: var(--form-element-invalid-border-color);
    width: 2.25em;
    height: 1.25em;
    border: var(--border-width) solid var(--border-color);
    border-radius: 1.25em;
    background-color: var(--background-color);
    line-height: 1.25em;
}
```
