### ISSUE TITLE
Is it possible to have a vertical nav sidebar with no modifications to the CSS?

### ISSUE THREAD

**Issue by gerardmarquina** [picocss/pico#49]
doing aside>nav eats up half the screen in a container

**Comment by ajusa** [comment]
I think what they want is the same as the nav that the pico docs have - a sticky vertical sidebar. 
For what it's worth, the first thing I tend to do after downloading pico is add some custom CSS (usually with flexbox) to support a sidebar, since it is a *super* common use case. You can use it for menus, to display additional information. 

It's pretty easy to do with custom CSS, but if Pico had it built in that would be very cool. Obviously, if it goes against the Pico spirit don't add it, but maybe an example showing how to get a similar effect with custom CSS would be nice.

**Comment by ajusa** [comment]
The snipped I've been using for a very simple grid is this:
```css
          .x1 { flex: 0 0 100% }
          .x2 { flex: 0 0 calc(1/2 * 100%) }
          .x3 { flex: 0 0 calc(1/3 * 100%) }
          .x4 { flex: 0 0 calc(1/4 * 100%) }
          .x6 { flex: 0 0 calc(1/6 * 100%) }
          .x8 { flex: 0 0 calc(1/8 * 100%) }
          .xg { flex: 1 0 auto }
          .x-center   { align-items: center; }
          @media (min-width: 992px) { 
            .x { display: flex; }
            .x > * + * {margin-left: 2rem}
          }
```
Loosely based on https://jxnblk.com/x, which is why the class names all start with x.
