### ISSUE TITLE
Use :user-invalid and :user-valid pseudo-classes to indicate visually when client-side validation has failed for an input after user interaction

### ISSUE THREAD

**Issue by bobby** [picocss/pico#621]
## Describe the issue

This issue is a follow-on to #47, but proposes the use of [`:user-valid` and `:user-invalid`](https://developer.mozilla.org/en-US/docs/Web/CSS/:user-invalid#browser_compatibility) pseudo-classes in addition to the `aria-*` attributes to apply valid/invalid styles to an input.
  
### Current Behavior

Currently, when doing client-side validation using HTML attributes (no JavaScript), an invalid user input entry is not highlighted visually.

### Expected Behavior

I would expect client-side validated inputs with which the user has interacted (indicated by the `:user-valid` or `:user-invalid` pseudo-classes) to show the proper validation styling.

### Reproduction URL

https://jsfiddle.net/L2p4rmy1/1/

### Environment

As linked above, the necessary pseudo-classes are supported across all major browsers.

**Comment by Yohn** [comment]
[Codepen Example](https://codepen.io/Yohn/pen/xxvMrvo)

Heres some css to make this work for :user-valid and :user-invalid

```css
input:user-valid,
input:user-invalid {
	padding-right: calc(1.5em + .75rem);
	background-repeat: no-repeat;
	background-position: right calc(.375em + .1875rem) center;
	background-size: calc(.75em + .375rem) calc(.75em + .375rem);
}
textarea:user-valid,
textarea:user-invalid {
	padding-right: calc(1.5em + .75rem);
	background-position: top calc(.375em + .1875rem) right calc(.375em + .1875rem);
	background-repeat: no-repeat;
	background-size: calc(.75em + .375rem) calc(.75em + .375rem);
}
input:user-invalid,
textarea:user-invalid {
	border-color: var(--pico-form-element-invalid-border-color);
	background-image: var(--pico-icon-invalid);
}
input:user-valid,
textarea:user-valid {
	border-color: var(--pico-form-element-valid-border-color);
	background-image: var(--pico-icon-valid);
}
```

And then to add the text after the element you can put a `<small data-invalid="This is invalid" data-valid="validation passed!"></small>` after the element

```css
/********** To include a message after the element with info ************/
input:user-valid + small[data-valid]::after,
textarea:user-valid + small[data-valid]::after {
	content: attr(data-invalid);
	color: var(--pico-form-element-valid-border-color);
}
textarea:user-invalid + small[data-invalid]::after,
input:user-invalid + small[data-invalid]::after {
	content: attr(data-invalid);
	color: var(--pico-form-element-invalid-border-color);
}

input:user-valid + small[data-valid]::after,
input:user-invalid + small[data-invalid]::after,
textarea:user-valid + small[data-valid]::after,
textarea:user-invalid + small[data-invalid]::after {
	display:block;
}
```
