### ISSUE TITLE
Accordion chevron padding

### ISSUE THREAD

**Issue by laurimiller** [picocss/pico#653]
I ran into an issue with long accordion headings in the summary tags pushing the chevron onto the next line or out of the button element on certain screen sizes. 

I'm wondering if there's an easy way I could add padding to either the summary tag or the ::after element in order to force the text to wrap and have the chevron stay inline with the first row of text?

<img width="562" alt="Image" src="https://github.com/user-attachments/assets/9279e3e6-7760-4b80-a22a-f34c7bf4a4cc" />

<img width="545" alt="Image" src="https://github.com/user-attachments/assets/56fda8b7-c405-4ad9-9160-018fcc234302" />

  
### Environment
Mac OS, Firefox 135.0b6

**Comment by Yohn** [comment]
The following would need a little more testing, but should work.

```css
details summary {
  position: relative;
}

details summary::after {
  float: none;
  position: absolute;
  top: calc(var(--pico-block-spacing-vertical) * .5);
  right: calc(var(--pico-block-spacing-horizontal) * .5);
}
```
