### ISSUE TITLE
Add a submit button for Search field

### ISSUE THREAD

**Issue by cara-tm** [picocss/pico#95]
Maybe the Search field need a Submit button:

    
    <label for="search">Search
		<input type="search" id="search" name="search" placeholder="Search">
		<input aria-label="Find" type="submit" name="search_submit" value=""> 
    </label>

And the corresponding rules:

    input[type="search"] {
        padding-left: calc(var(--form-element-spacing-horizontal) + 1.75rem)
    }

    input[type="search"] + input[type="submit"] {
        position: absolute;
        top: calc(var(--form-element-spacing-vertical) * 2.5);
        left: 0;
        width: auto;
        min-width: 2.5rem;
        height: 3rem;
        margin: 0;
        padding: 0;
        background: transparent;
        border: none;
        border-top-left-radius: 5rem;
        border-bottom-left-radius: 5rem
    }

**Comment by lucaslarroche** [comment]
I like this idea too.
It should probably be a separate SCSS file to be disabled.

It can be more generic (not only for search, but for all inputs text):

```CSS
input:not([type=checkbox]):not([type=radio]):not([type=range]):not([type=file]) + input[type="submit"],
input:not([type=checkbox]):not([type=radio]):not([type=range]):not([type=file]) + input[type="button"],
input:not([type=checkbox]):not([type=radio]):not([type=range]):not([type=file]) + button,
input:not([type=checkbox]):not([type=radio]):not([type=range]):not([type=file]) + a[role="button] {
   ...
}
```
> Another crazy long CSS selector 😬...

We might want a visible button [like here](https://getbootstrap.com/docs/5.1/forms/input-group/#button-addons).
Not so easy without a class on the label if we want to properly manage all the states (hover, focus, invalid).
